spring.config.import=classpath:actuator.properties,classpath:openapi.properties
spring.application.name=springpr-ai-chatclient
springpr.app.id=${spring.application.name}
server.port=8084

spring.sql.init.mode=always

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/postgresml
spring.datasource.username=myappuser
spring.datasource.password=mypassword

# pg_vector feature
spring.ai.postgresml.embedding.create-extension=true
spring.ai.postgresml.embedding.vector-type=pg_vector
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true

# Chat Memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# Model
spring.ai.model.embedding=ollama
#postgresml

# MCP Client
#spring.ai.mcp.client.enabled=true
spring.ai.mcp.server.expose-mcp-client-tools=true
spring.ai.mcp.client.streamable-http.connections.server1.url=http://localhost:8083

spring.ai.chat.client.tool-calling.enabled=true
spring.ai.chat.client.tool-search-advisor.enabled=true
spring.ai.chat.client.tool-search-advisor.tool-index-type=vector

# Acturator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
