spring.config.import=classpath:actuator.properties,classpath:openapi.properties
spring.application.name=springpr-ai-mcp-github
springpr.app.id=${spring.application.name}
server.port=8085

# Application settings for GitHub MCP server
# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring.main.banner-mode=off
logging.pattern.console=

# MCP server configuration
spring.ai.mcp.server.version=0.0.1
#spring.ai.mcp.server.stdio=true

#spring.ai.mcp.server.stdio=true

# Web server configuration (disable for STDIO mode)
#spring.main.web-application-type=none

# Logging configuration
logging.file.name=./target/github-server.log

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
