spring.config.import=classpath:actuator.properties,classpath:openapi.properties
spring.application.name=springpr-ai-mcp-meetingcheduler
springpr.app.id=${spring.application.name}
server.port=8083

spring.ai.mcp.server.name=scheduler-server
spring.ai.mcp.server.version=0.0.1

#spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC