#########################
### OpenAPI endpoints ###
#########################
springdoc.api-docs.path=/${springpr.app.id}/v3/api-docs
#springdoc.api-docs.enabled=true
#(comma separated)
#springdoc.packages-to-scan=*
springdoc.show-actuator=true

# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/${springpr.app.id}/swagger-ui.html
# Enable or disable Swagger UI
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.configUrl=/v3/api-docs/swagger-config

#springdoc.use-management-port=false
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
#management.endpoints.web.exposure.include=*

### OpenAPI Document Path Filtering ###
#springdoc.paths-to-match=/variables/**,/api/employees/**,/api/v1/employees/**,/api/v1/resources/**
